@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!include <office/Concepts/service_application>

left to right direction

AddSystemTag("conApp", $sprite="service_application", $legendText="system")

Person(user, "App User", "Pengguna Aplikasi Posyandu")
System(posyandu, "Posyandu System", "Sistem aplikasi Posyandu", $tags="conApp")
System(eKMS, "eKMS System", "elektronik Kartu Menuju Sehat", "", $tags="conApp")
System_Ext(servana, "Servana System", "lingkungan pengembangan yang luas & stabil")
Person_Ext(user2, "Vendor IT", "Vendor yang Maintenace Sistem")

Rel(user, posyandu, "Uses", "HTTPS")
Rel_L(posyandu, eKMS, "Uses", "HTTPS/REST")
Rel_R(posyandu, servana, "Uses", "HTTPS/REST")
Rel_U(user2, servana, "Uses", "HTTPS")
SHOW_LEGEND()
@enduml
